version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/card-capture-fe/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
