version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/card-capture-fe/card-capture
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
