name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v2

      - name: 레포지토리 파일 목록 출력
        run: ls -al

      - name: package.json 존재 여부 확인
        working-directory: ./card-capture
        run: test -f package.json || { echo "package.json not found"; exit 1; }

      - name: Node.js 설정
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 의존성 설치
        working-directory: ./card-capture
        run: npm install

      - name: 테스트 실행
        working-directory: ./card-capture
        run: npm test

      - name: 프로젝트 빌드
        working-directory: ./card-capture
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          echo "빌드 중 린트 생략"
          CI= npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v2

      - name: 레포지토리 파일 목록 출력
        run: ls -al

      - name: package.json 존재 여부 확인
        working-directory: ./card-capture
        run: test -f package.json || { echo "package.json not found"; exit 1; }

      - name: Node.js 설정
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 의존성 설치
        working-directory: ./card-capture
        run: npm install

      - name: 프로젝트 빌드
        working-directory: ./card-capture
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_JWT_TOKEN: ${{ secrets.NEXT_PUBLIC_JWT_TOKEN }}
        run: npm run build

      - name: 서버에 배포
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | sed 's/\\n/\n/g' > deployment_key.pem
          chmod 400 deployment_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no -i deployment_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
            set -e

            BASE_DIR="/home/${{ secrets.SERVER_USER }}/card-capture-fe"
            PROJECT_DIR="$BASE_DIR/card-capture"

            echo "BASE_DIR: $BASE_DIR"
            echo "PROJECT_DIR: $PROJECT_DIR"

            if [ -d "$BASE_DIR" ]; then
              rm -rf "$BASE_DIR"
            fi

            mkdir -p "$BASE_DIR"
            cd "$BASE_DIR"

            echo "레포지토리 클론 중..."
            git clone $REPO_URL . || { echo "Git clone failed"; exit 1; }

            cd "$PROJECT_DIR"

            echo "현재 디렉토리: $(pwd)"
            ls -la

            if [ ! -f "package.json" ]; then
              echo "Error: package.json not found"
              exit 1
            fi

            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env
            echo "NEXT_PUBLIC_JWT_TOKEN=${{ secrets.NEXT_PUBLIC_JWT_TOKEN }}" >> .env

            npm install
            npm run build

            if pm2 list | grep -q "card-capture-fe"; then
              pm2 restart card-capture-fe
            else
              pm2 start npm --name "card-capture-fe" -- start
            fi
          EOF
